spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Security-App
    username: postgres
    password: ujLG5xV4
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        fromat_sql:true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
application:
  jwt:
    secret-key: 6150645367566B5970337336763979244226452948404D6251655468576D5A71
 
    
